#+MACRO: ts (eval(mwp-get-ts+7  'org-mwp-classtimes-calibrate 2))
#+STARTUP: customtime
#+TITLE: HIS389: Science, Technology, Modernity
#+ODT_STYLES_FILE: "/home/matt/.emacs.d/Templates/syl-temp-2019.odt"
#+ORG_LMS_COURSEID: 112215
# #+ORG_LMS_ASSIGNMENTS: ~/DH/Assignments.org
#+IS_PUBLIC: t

* COMMENT Setup
#+begin_src emacs-lisp :results none
;; (org-lms-setup)
(org-lms-post-syllabus)
#+end_src

* Logistics

| *Instructor:*   | Matt Price             |
| *Email:*        | matt.price@utoronto.ca |
| *Office Hrs:*   | T Th 5-6, [[http://map.utoronto.ca/utsg/building/033][SS 3077]]      |
| *Meeting Times* | T Th 4-5, [[http://map.utoronto.ca/utsg/building/033][SS 1088]]      |

* Course Description
What does it mean to be modern? We use words like “modern,” “modernity,” and “modernism” to mark a fundamental boundary between our era and all that came before it (or lies outside of it); but most of us are hard-pressed to offer a solid account of what exactly this boundary is. The precise nature of the rupture between modernity and pre- or non-modernity is a vast topic, and this course will not attempt to answer it fully. Instead, we will investigate the question of modernity with a particular eye to the history of science and technology. We will focus on a few key developments which took place in or around the Nineteenth Century, but will also wander into the first decades of the Twentieth. The organization of the course is an implicit argument that certain phenomena, namely:

1. /a fundamental shift in the nature of daily experience;/
2. /an order-of-magnitude expansion of the power of the State/; and
3. /a tremendous growth in the enterprise of Western science and technological production/

were intimately related. Over the coming months we will investigate these themes using a wide variety of sources, from literary texts to scientific papers, from technical history to cultural theory. A particularly urgent goal of the course is to integrate new approaches to the history of science and technology with recent developments in cultural history. For the most part we will focus on European developments, but we will occasionally range our somewhat further, looking in particular at events in the United States and in the European, especially British and French, empires.

This course asks difficult questions and demands a substantial commitment from students; in return, it provides a fairly sophisticated set of tools for thinking about history.

* Course Format
This course is nominally a lecture class, but enrollment is low, the subject matter is complex, and there's a lot to talk about. We will take advantage of the cozy setting to pursue a mix of lectures and discussion. 

* Prerequisites
  :PROPERTIES:
  :CUSTOM_ID: prerequisites
  :END:

Background in modern European history and some background or interest in the history of science are both highly desirable. The course includes a small amount of technical content, which students will be asked to at least puzzle their way through; it also includes some fairly sophisticated and theoretical secondary sources. 

Class Format:

History Department policy provides for two hours of class time at the third year (Tuesday/Thursday 4-5). I have scheduled two additional hours for optional discussion periods (Tuesday/Thursday 5-6). Though your grade does not include a participation component, attendance at discussions is nonetheless /strongly/ advised. We will be reading difficult texts, and lectures will not cover all the issues they raise. /Your active engagement with the course material is an essential part of the course./

* Course Requirements:
Your grade consists of the following components:

|   | Assignment       | Due Date | Weight |
|---+------------------+----------+--------|
| # | Midterm "Exam" 1 | <2017-02-08 Wed>  |     25 |
| # | Midterm "Exam" 2 | <2019-03-15 Fri>  |     25 |
| # | Paper Proposal   | <2019-03-21 Thu>  |     10 |
| # | Final Paper      | <2019-04-08 Mon>  |     30 |
| # | Participation    | n/a      |     10 |
|---+------------------+----------+--------|
|   |                  |          |    100 |
#+TBLFM: @>$>=vsum(@I..@II)
# #+TBLFM: $>=$>>(100/@>$4)::@>$>>=vsum(@I..@II)

The "*Exams*" are take-home assignments somewhere between an ordinary midterm and a short paper. Though untimed, they are intended to be written in a finite time period over the course of just a few days. Each exam will ask you to write approximately two short essays in response to the class readings.

The *Paper Assignment* asks you to explore one or more of the course texts on your own. Using the class bibliography as a starting point if you wish, you will write a medium-length paper (10-12pp) analyzing, interpreting, and contextualizing the primary text. A paper proposal is due several weeks before the paper itself.  

Extensions granted for medical reasons only. Late assignments will be deducted 3% per day, with the exception of the take-home exams, which /will be marked “0” if not handed in by 5:00 PM on the due date/. Please note: the paper proposal is /required/, and term papers will not be accepted if a proposal is not handed in.

* Course Texts

Most of our required readings are primary sources and will generally be made available online, but I will make heavy use of recommended readings in my lectures. You may profit from having your own copies of some of the following texts:

- James c. Scott, /Seeing Like a State/ 1998 ([[https://search.library.utoronto.ca/details?8846532][Library]]).
- Marshall Berman, /All That Is Solid Melts Into Air/ (Penguin, 1982)
- J.W.v. Goethe, /Faust I and II/ (Princeton, N.J.: Princeton Univ Press)
- Wolfgang Schivelbusch, /The Railway Journey/ (Berkeley: University of California Press, 1987)
- Michel Foucault, /Discipline and Punish/ 

* Accessibility
The University provides academic accommodations for students[with disabilities in accordance with the terms of the Ontario Human[Rights Code. For information on services and resources, see
[[http://www.studentlife.utoronto.ca/as]]

* Academic Integrity

The University of Toronto treats cases of plagiarism very seriously. The
/Code of Behaviour on Academic Matters/ (http://www.governingcouncil.utoronto.ca/Assets/Governing+Council+Digital+Assets/Policies/PDF/ppjun011995.pdf) outlines the behaviours that constitute academic dishonesty and the procedures for addressing academic offenses. If you have questions or concerns about what constitutes appropriate academic behaviour or research and citation methods, you should seek information from your instructor or other university resources. See http://www.artsci.utoronto.ca/osai/students.

* Outline
This outline is *a work of fiction*. We will begin with this template but almost certainly not cover all of these topics; where it seems appropriate, we may stop and read more about any of them, or skip topics you have no interest in. Expect things to change!

** {{{n}}} ({{{ts}}}) modernity, modernism, modernization  --tragic and comic views of modernity -- introduction to science studies  
- We'll discuss
  - Legibility
  - knowledge and state power -- the legible city -- mapping territory -- forests, trees, and honeybees
- *Recommended Readings:*
  - Start Goethe, /Faust/ and /Frankenstein/ (see next week) 
  - Berman, /All That Is Solid/, 15-36 (Introduction)
  - Scott, /Seeing Like a State/, 1-8 (“Introduction”), 11-52 (“Nature and Space”)
** {{{n}}} ({{{ts}}}) Enlightenment Calculation  
- We'll discuss
  - Progress and Human Nature
  - Division of labour -- revolution and calculation -- democracy and authority
- *Required Readings:*
  - *Condorcet, “Sketch of the Historical Progress of the Human Mind” Ch. 10.  
  - *Adam Smith, /Wealth of Nations/, I.i-I.ii. [[https://archive.org/details/wealthofnationss01smituoft/page/n23][PDF at Internet Archive]].
  - *Lorraine Daston, “[[https://search-proquest-com.myaccess.library.utoronto.ca/docview/198821138?pq-origsite=summon][Enlightenment Calculations]]”,/ Critical Inquiry/ 21 (1994): 182-202.
- /Recommended:/
  - Habermas, “Structural Transformation of the Public Sphere”
  - E.P. Thompson, “[[https://www-jstor-org.myaccess.library.utoronto.ca/stable/649749?seq=1#metadata_info_tab_contents][Time, Work-Discipline, and Industrial Capitalism]]” /Past and Present/ 38 (1967)
  - Michael Adas, /Machines as the Measure of Men/, esp. pp.59-68.
** {{{n}}} ({{{ts}}}) Science, Knowledge, and Change as Tragedy
- We'll discuss
  - Romance of science
  - Tragedies of Development
  - Faustian bargains
- *Required Readings:*
  - Mary Shelley, /Frankenstein/. Find a used copy or try [[https://www.gutenberg.org/ebooks/84][Project Gutenberg]]; ch. 3-6, 11-16, 24.
  - J.W. v. Goethe, /Faust/, 9-23, 32-66, 83-119, 279-305
- *Recommended Readings:*
  - Berman, /All That is Solid/, 37-86
** {{{n}}} ({{{ts}}}) Science as Tragedy 2 
Continuing the same conversation
** {{{n}}} ({{{ts}}}) Romantic Science
- We'll discuss
  - holism, pantheism, nature
  - intuition, exactitude, empiricism
- *Required Readings:*
  - Nichols, Ashton. “The Loves of Plants and Animals: Romantic Science and the Pleasures of Nature,” November 1, 2001. https://www.rc.umd.edu/praxis/ecology/nichols/nichols.html
  - Humboldt, Alexander von. "Preface" in /Cosmos. a Sketch of a Physical Description of the Universe/. Otte, E. C., trans. H. G. Bohn, 1849. http://archive.org/details/bub_gb___pOsDBLVvkC. 
- *Recommended Readings:*
  - Stuart Strickland, “[[https://muse-jhu-edu.myaccess.library.utoronto.ca/article/10799][The Ideology of Self-Knowledge and the Practice of Self-Experimentation]]” /Eighteenth -Century Studies/ 31:4 (1998) 453-471.
** {{{n}}} ({{{ts}}}) Utopia, here and away
- We'll discuss
  - societies perfect and imperfect
  - modernization for rich and poor
  - sewers, prostitution, and other public health issues 
  - crystal palaces and their critics
- *Required Readings:*
  - Etienne Cabet, /Voyage to Icaria/. Selections.
  - August Comte, "The Positive Organization of Social Existence."
  - Robert Reid, /[[https://www-fulcrum-org.myaccess.library.utoronto.ca/concern/monographs/8623hx80d][Paris Sewers and Sewermen]]/, 25-52.
- Recommended Readings:
  - Berman, /All That Is Solid/, 131-172 (Baudelaire), 173-286 (Petersburg)
  - Scott, /Seeing Like a State,/ 53-83 (Cities, People, and Language)
  - John Merriman, “The Two Cities of Baron Hausmann.”
  - Baudelaire, /Paris Spleen/, selections.
  
** {{{n}}} ({{{ts}}}) Space And Time in the World of Steam (Railroad, Telegraph, Empire)
We'll discuss:
  - time dilation, space contraction
  - mechanisms of empire
- *Required Readings:*
  - Wolfgang Schivelbusch, "Railway Space and Railway Time" in /[[https://ebookcentral-proquest-com.myaccess.library.utoronto.ca/lib/utoronto/detail.action?docID=1686847#goto_toc][The Railway Journey]]/. 
  - Laxman D. Satya, “British Imperial Railways in Nineteenth Century South Asia.” Economic and Political Weekly, June 5, 2015, 7–8. https://www.epw.in/journal/2008/47/special-articles/british-imperial-railways-nineteenth-century-south-asia.html.
- *Recommended Readings:*
  - Bruce J. Hunt, “Doing Science in a Global Empire: Cable Telegraphy and Electrical Physics in Victorian Britain,” in B. Lightman, /Victorian Science in Context/ (Chicago: University of Chicago Press, 1997) 312-333

**  {{{n}}} ({{{ts}}}) Steam-Age Calculation
- We'll Discuss:
  - Minds and Machines
  - Gender and Intelligence
- *Required Readings:*
  - Charles Babbage on the Difference Engine: “On the Application of Machinery to the Purpose of Calculating and Pringing Mathematical Tables” and “The Science of Number Reduced to Mechanism,” both in /Works of Charles Babbage, /v. II.
  - Simon Schaffer, “Babbage's Dancer and the Impresarios of Mechanism,” in Spufford & Uglow, /Cultural Babbage/ (London: Faber, 1997), 53-80.
** {{{n}}} ({{{ts}}}) Thermodynamic Worldview 1: conservation 
- We'll discuss
  - The First Law (Joule and Helmholtz)
  - Thermodynamic Worldview
  - The Second Law (Entropy, Kelvin)
- *Required Readings:*
  - Helmholtz, H. “On the Interaction of Natural Forces.” /The London, Edinburgh, and Dublin Philosophical Magazine and Journal of Science/ 11, no. 75 (January 1, 1856): 489–518. https://www-tandfonline-com.myaccess.library.utoronto.ca/doi/abs/10.1080/14786445608642114.
  - William Thomson, “On the age of the sun's heat,” /MacMillan's Magazine/ 5 (1862), 288-93. https://zapatopi.net/kelvin/papers/on_the_age_of_the_suns_heat.html
- Recommended Readings:
  - Wise and Smith, /Energy and Empire/,
  - *Robert M. Brain and M. Norton Wise, “Muscles and Engines”, repr. In Biagioli, ed, /The Science Studies Reader/ (New York: Routledge, 1999 [1994]), 51-66.
  - Anson Rabinbach, “Transcendental Materialism” in /The Human Motor /(Berkeley: UC Press, 1992)
  - Crosbie Smith, / The Science of Energy /(selections)

** {{{n}}} ({{{ts}}}) Thermodynamic Worldview 2: progress and decay
Continuation of the previous conversation
** {{{n}}} ({{{ts}}}) Evolution 1 
- We'll discuss
  - Darwin the Romantic?
  - Darwin the imperialist?
  - Progress? Degeneration?
- *Required Readings:*
  - Charles Darwin, /On the Origin of Species/ (selections)
- Recommended Readings:
  - Galton, “The Possible Improvement of the Human Breed” from /Essays in Eugenics/ (1909) 35-43
** {{{n}}} ({{{ts}}}) Evolution 2 
Continuation of the previous conversation
** {{{n}}} ({{{ts}}}) Normalcy, Deviance, and Statistical Persons  
- We'll discuss
  - rise of statistical thinking
  - normal as ideal
  - individuals and aggregations
- *Required Reading:*
  - Alphonse Bertillon, “The Bertillon System,” [cite].
  - Francis Galton, “Probability, the Foundation of Eugenics,” The Herbert Spencer Lecture June 5, 1907 (Oxford: Clarendon Press, 1907).
- *Recommended Reading:*
  - Theodore M. Porter, “The Laws that Govern Chaos,” in /The Rise of Statistical Thinking, 1820-1900/ (Princeton: Princeton UP, 1986) 40-70.
  - Lennard J. Davis, “Constructing Normalcy” in /The Disability Studies Reader/ (New York: Routledge, 1997), 2-28
  - *Deborah Coon, “Standardizing the Subject: Experimental Psychologists, Introspection, and the Quest for a Technoscientific Ideal,” /Technology and Culture /(1993), 757-783.
  - Mark Seltzer, “Statistical Persons” in /Bodies and Machines/ (New York: Routledge, 1992) 93-118
** {{{n}}} ({{{ts}}}) READING WEEK
** {{{n}}} ({{{ts}}}) READING WEEK
** {{{n}}} ({{{ts}}}) From Power of Death to Power of Life  
- We'll discuss
  - State power and surveillance -- the gentle way in punishment -- docile subjects
- *Required Readings:*
  - *Michel Foucault, “Right of death and Power over Life” from /History of Sexuality, vol. 1/
- *Recommended Readings:*
  - Scott, /Seeing Like a State/, 11-52 (“Nature and Space”)
  - Michel Foucault, /Discipline and Punish/.
  - Michel Foucault, *History of Sexuality, v. 1*
** {{{n}}} ({{{ts}}}) Degeneration
- Herbert Spencer, /The Principles of Sociology, vol 1/ (third edition, 1885) (Westport, CT: Greenwood Press, 1975[1897]) 3-7, 437-450.
- Cesare Lombroso, “The Criminal Type in Women and its Atavistic Origins” in /[[https://archive.org/details/femaleoffender00lomb/page/n7][The Female Offender]]/ (New York: Philosophical Library, 1958) 103-115. 
- Francis Galton, “Eugenics: Its Definition, Scope and Aims” /American Journal of Sociology/ 10:1 (1904) 1-6
- Nordau, “Fin-de-Siecle” in /Degeneration/ ([[https://archive.org/details/femaleoffender00lomb/page/n7][one of many archive.org editions]]) 1-44.
- *Recommended Reading*
- Daniel Pick, /Faces of Degeneration/ (selections)
** {{{n}}} ({{{ts}}}) The Positive Science of Society
- August Comte, “Necessity and Opportuneness of This New Science [social physics]” from /Cours de Philosophie Positive/ in G. Lenzer, ed., /Auguste Comte and Positivism: The Essential Writings/ ( New York: Harper & Row, 1975)
- Emile Durkheim, “Division of Labour in Society: Consequences” in R N. Bellah, ed, /Emile Durkheim on Morality and Society/ (Chicago: University of Chicago Press, 1973[1893]), 114-133.
** {{{n}}} ({{{ts}}}) Photography and Mechanical Reproduction  
- We'll discuss
  - Image of a New World
  - Commodity Culture
  - Markets, Utopia, and the World of Things
- *Required Readings:*
  - Walter Benjamin, “The Work of Art in the Age of Mechanical Reproduction”, in /Illuminations/
    - Marx, “Commodity Fetishism” in /Capital/
- Recommended Readings:
  - Jonathon Crary, /Techniques of the Observer/
  - Bernard Cohn, "The transformation of Objects into Artifacts, Antiquities, and Art in Nineteenth-Century India"



** {{{n}}} ({{{ts}}}) Machine Culture 1: The Body as Machine  
- We'll discuss
  - Mechanization of the body
- *Required Readings:*
  - Etienne-Jules Marey (selections TBD)
  - Edward Muybridge (selections TBD)
- *Recommended Readings:*
  - Franz Reuleaux, /The Kinematics of Machinery/
  - Mark Seltzer, /Bodies and Machines/
  - Anson Rabinbach, /The Human Motor/
  
** {{{n}}} ({{{ts}}}) Machine Culture 2: Yankee Ingenuity
- We'll discuss:
  - science, religion, race, and manifest destiny
  - standards, guns, and bicycles
- *Required Readings:*
  - Mark Twain, /Connecticut Yankee in King Arthur's Court/ (selections TBD)

** {{{n}}} ({{{ts}}}) Subjects Scientific and Hysteric
- We'll discuss:
  - sciences of gender
  - limits of reason
- Mark Micale, "Hysteria Female/Hysteria Male"
- Sigmund Freud, “Project for a scientific Psychology” /Standard Edition of the Complete Psychological Works, vol. 1/ (Selections)
- Hugo Munsterberg, “Illusions” in /On the Witness Stand. Essays in Psychology and Crime/ (New York: Clark Boardman Co, 1925) 15-36.
- Wilhelm Wundt, “Consciousness and Attention” in /Outlines of Psychology/ (New York: Gustav E. Stechert, 1897) 203-223.

** {{{n}}} ({{{ts}}}) Risk Societies
- We'll discuss
  - Risk, Benefit, Freedom, Slavery, Bodies
- *Required Readings:*
  - Jonthan Levy, "The Perils of the Seas" in /Freaks of Fortune/ (2012) 21-39.
  - Caitlin Rosenthal, "Human Capital" in /Accounting for Slavery/ (2018) 121-156.
** {{{n}}} ({{{ts}}}) Imperial Science 1
- We'll discuss
  - science /in/ and /as/ empire
- *Required Reading:*
  - Bruno Latour, “Centres of Calculation” in /Science in Action/
  - Helen Watson-Verran and David Turnbull, "Science and Other Indigenous Knwoledge Systems" (1995). See copy [[https://www.researchgate.net/publication/312371585_Science_and_other_indigenous_knowledge_systems][here]].
- *Recommnded Reading:*
  - 
  - Stephen Kern, “Distance” in /The Culture of Time and Space 1880-1920/
   (1983), 211-240.

**  {{{n}}} ({{{ts}}}) Imperial Science 2 
** {{{n}}} ({{{ts}}}) Modernist Math and Physics  
- We'll discuss
  - Relativity -- clocks and rods -- railroad time -- intuitionism -- pure abstraction

- *Required Readings:*
  - Albert Einstein, “On the Electrodynamics of Moving Bodies.”
  - Peter Galison, /Einstein's Clocks/
  - Recommended Readings:
  - Herbert Mehrtens, /Moderne Sprache Mathematik/.
** {{{n}}} ({{{ts}}}) World War I & Finale  
[this has spilled out into an extra week -- we may remove something so that we can get here in time)
  - Science of War
  - Moral equivalents -- war and utopia -- exuberance of the state
- *Required Readings:*
  - William James, “The Moral Equivalent of War.”
  - Wichard von Moellendorf, “Planwirtschaft.”


* COMMENT Leftovers (some repetition)
** {{{n}}} ({{{ts}}}) New Media  
- We'll discuss
   Lisa Gitelman, /Scripts, Grooves, and Writing Machines. Representing
   Technology in the Edison Era/ (Palo Alto: Stanford UP, 1999).
   Chapters 2 (62-96), 5 (184-218)
   Recommended:
   Friedrich Kittler, /Gramophone, Film, Typewriter/
** {{{n}}} ({{{ts}}}) More Enlightenment (see "similar syllabus" for ideas) 
** {{{n}}} ({{{ts}}}) Information  
** {{{n}}} ({{{ts}}}) Technoscientific Aesthetics  
- We'll discuss
  - Tones and noise -- colors, motion, effort
  - New Media System
  - Film, gramophone, typewriter
- *Required Readings:*
  - Hermann von Helmholtz, “Sensations of Tone”
  - Timothy Lenoir, “Optics... & the Politics of Vision”, in /Instituting Science/ (1998)
  - Sidney Kwiram “Tones for Thought,” (Honors Thesis, Harvard University, 1999).
  - something from Materialities of Communication?
- Recommended Readings:
  - Friedrich Kittler, /Film, Gramophone, Typewriter/
** {{{n}}} ({{{ts}}})  Normalcy: slightly different version 
- We'll discuss
  - Statistical Persons
  - Normalcy 2
- Hysteria
  - Readings:
- Required:
  - Francis Galton, “Probability, the Foundation of Eugenics,” The Herbert Spencer Lecture June 5, 1907 (Oxford: Clarendon Press, 1907).
  - Alphonse Bertillon, “The Bertillon System,” [cite].
  - Theodore M. Porter, “The Laws that Govern Chaos,” in /The Rise of Statistical Thinking, 1820-1900/ (Princeton: Princeton UP, 1986) 40-70.
- /Recommended:/
  - *Deborah Coon, “Standardizing the Subject: Experimental Psychologists, Introspection, and the Quest for a Technoscientific Ideal,” /Technology and Culture /(1993), 757-783.
  - Mark Seltzer, “Statistical Persons” in /Bodies and Machines/ (New York: Routledge, 1992) 93-118
** {{{n}}} ({{{ts}}}) Technoscientific Aethetics  
- We'll discuss
Hermann von Helmholtz, “Introduction” to /Sensations of Tone/ (New York:
Dover, 1954[1877]), 1-6.
Timothy Lenoir, “The Politics of Vision: Optics, Painting, and Ideology
in Germany, 1845-95”, in /Instituting Science/ (1998)
Sidney Kwiram “Tones for Thought,” (Honors Thesis, Harvard University,
1999), 1-27, 38-81
** {{{n}}} ({{{ts}}})  Imperial Science 1  
- We'll discuss
  - Networks and Centres of Calculation
  - Imperial Science 2
  - Local Knowledge Under Siege
- *Required Readings:*
  - Bruno Latour, “Centres of Calculation” in /Science in Action/.
  - Helen Verran, “Science as an Indigenous Knowledge System”
- collecting?
- Recommended Readings:
** {{{n}}} ({{{ts}}}) Recap and Moving Forward  
- We'll discuss
   no readings
** {{{n}}} ({{{ts}}}) Modernism in Math and Physics  
- We'll discuss
   Peter Galison, “Einstein's Clocks” /Cr/
   Dedekind
   Hilbert
   Einstein
** {{{n}}} ({{{ts}}}) Science and Totalitarianism  
:PROPERTIES:
:GRADE:    1
:END:
- We'll discuss
   Mario Biagioli
   Horkneimer & Adorno
   Scott

#+begin_src emacs-lisp
(let ((mylist '(2 1)))
  (cl-loop for i from 3 to 7
           do
           (add-to-list 'mylist i ))
(nth 2 mylist))
#+end_src

#+RESULTS:
: 5

#+begin_src emacs-lisp
(mwp-get-ts+7 'mwp-classtimes-calibrate)
#+end_src

#+RESULTS:
: <2019-01-10 Thu>

#+begin_src emacs-lisp :results code
(add-hook 'mwp-show-macros-final-hook #'hack-local-variables t)
(run-hooks 'mwp-show-macros-final-hook)
;; mwp-show-macros-final-hook
mwp-classtimes-calibrate
#+end_src


#+RESULTS:
#+begin_src emacs-lisp
("<2019-01-03 Thu>" "<2019-01-01 Tue>")
#+end_src

#+begin_src emacs-lisp :results code
;;(hack-local-variables)
mwp-classtimes-calibrate
(alist-get 'mwp-classtimes-calibrate file-local-variables-alist)
#+end_src

#+RESULTS:
#+begin_src emacs-lisp
("<2019-01-03 Thu>" "<2019-01-01 Tue>")
#+end_src

#+begin_src emacs-lisp
(let ((l 
       (make-list 3 (format "<%s>" (format-time-string "%Y-%m-%d %a" )))))
  (symbol-name 'l))
#+end_src

#+RESULTS:
: l

* COMMENT old plans 
** Introduction (1)
- OK -- need to add stuff on theories of modernity, & to expand on “tragic” and “comic” views
- Steam Engine? Eiffel Tower? Pictures of Freud, Marx, Darwin?
- Foucault, “governmentality”;Weber, “spirit of capitalism”; Marx, “manifesto” & something else;
- Cohen, KM's thy of history;Elias, “civilizing process”
** Enlightenment (2)
- Not great
- Looks a bit dull -- need to spice it up a bit. More interesting enlightenment stuff -- maybe read darnton or something
- Stuff from Encyclopedie; Adam Smith
- Outram, “Enlightenment”; Darnton, ??; Daston, various
** todos from an old file (outdated)
JK216 .T713 2004X
tocqueville: social and political condition of france... essay --
seems good. Westminster review 25 (apr 18360 137-169);
ap4.w5 -- FOLUME MAY BE MISSING.
 JC229 .T775 2002
*Klemens von Metternich, */*Memoirs (letter to alex)*/DB80.8 .M57 A33
1970 V.1
/Joseph de Maistre/, “Essay o the gen princ of political constitution*/*
*JC229 .M213

* COMMENT Very similar first-semester plans from another file 
** 09-09
- Introduction
- modernity, modernism, modernization --tragic and comic views of modernity -- introduction to science studies
- Legibility
- knowledge and state power -- the legible city -- mapping territory -- forests, trees, and honeybees
- Required Readings:
- Start Goethe, /Faust/ (see Week 4)
- Berman, /All That Is Solid/, 15-36 (Introduction)
- Scott, /Seeing Like a State/, 1-8 (“Introduction”), 11-52 (“Nature and Space”)
** 16-09
- Enlightenment Calculation
- Progress and Human Nature
- Division of labour -- revolution and calculation -- democracy and authority
- *Required Readings: *
- *Condorcet, “Sketch of the Progress”
- *Adam Smith, /Wealth of Nations/, I.i-I.ii
- *Lorraine Daston, “Enlightenment Calculations”,/ Critical Inquiry/ 21 (1994): 182-202.
- /Recommended:/
- *E.P. Thompson, “Time, Work-Discipline, and Industrial Capitalism” /Past and Present/ 38 (1967)
** 23-09
- Enlightenment Continued
- Modernity and the Public Sphere
- Science and Romanticism
- The Romance of Science
- *Required Readings:*/ /
- *Habermas, “Structural Transformation of the Public Sphere”
- *Isaiah Berlin, /Roots of Romanticism/ (Selections)
- *Stuart Strickland, “The Ideology of Self-Knowledge and the Practice of Self-Experimentation” /Eighteenth -Century Studies/ 31`:4 (1998) 453-471.
- *Mary Shelley, /Frankenstein, /Chapter 3.
- Recommended Readings:
- Mary Shelley, /Frankenstein/.
- Bruce Sterling and William Gibson, /The Difference Engine/
** 30-12
** 30-09
- More Romanticism
- Faustian Bargains
- Faustian Bargains
- *Required Readings:*/ /
- J.W. v. Goethe, /Faust/, 9-23, 32-66, 83-119, 279-305
- Berman, /All That is Solid/, 37-86
** Week 5
** 07-10
- The World of Steam
- Engines of Progress
- Railway Journeys 1
- *Required Readings:*/ /
- *John Farey, “Treatise on The Steam Engine” (selections)
- Wolfgang Schivelbusch, The Railway Journey (through chapter 5)
** 14-10
- Thermodynamic Worldview I: Progress
- Work, Energy, and Waste
- The First Law (Joule and Helmholtz)
- *Required Readings:*
- *Hermann von Helmholtz, “On the Interaction of Forces in Nature,” in/ Science and Culture. Popular and Philosophical Essays/, ed. David Cahan (Chicago: University of Chicago Press, 1995), 18-45.
- Crosbie Smith, / The Science of Energy /(selections)
- M. Norton Wise, “Work and Waste I”
- Recommended Readings:
- Wise and Smith, /Energy and Empire/,
- *Robert M. Brain and M. Norton Wise, “Muscles and Engines”, repr. In Biagioli, ed, /The Science Studies Reader/ (New York: Routledge, 1999 [1994]), 51-66.
- Anson Rabinbach, “Transcendental Materialism” in /The Human Motor /(Berkeley: UC Press, 1992)
** 21-10
- The Evolutionary Idea
- Darwin's voyages
- “Darwinism”
- Robert Clambers, /Vestiges of the Natural History of Creation/ (Selections)
- Charles Darwin, /On The Origin of Species/ (Selections)
- Herbert Spencer, /The Social Organism/ (Selections)
- Francis Galton, “Eugenics: Its Definition, Scope and Aims” and “The Possible Improvement of the Human Breed”.
- From Power of Death to Power of Life
- Required Reading:
- Michel Foucault, “Biopower”
- Michel Foucault, /Discipline and Punish /(selections TBA)
** 04-11
- Utopias
- The Utopian Vision
- Paris and Petersburg: Sewers, Prostitutes, and other Public Health issues
- *Required Readings:*
- Etienne Cabet, “Voyage to Icaria” (Selections)
- Robert Reid, /Paris Sewers and Sewermen/, 25-52.
- Baudelaire, /Paris Spleen, /selections.
- Berman, /All That Is Solid/131-172 (Baudelaire), 173-286 (Petersburg)
- Recommended Readings:
- John Merriman, “Les deux Ville de Baron Haussmann.”
- Scott, /Seeing Like a State,/ 53-83 (Cities, People, and Language)
** 11-11
- More Utopias
- Chicago: Nature's Metropolis
- And their Critics
- Crystal Cities
- Cronon, /Nature's Metropolis/, “Grain” and “Meat”.
- Dostoevsky, /Notes From Underground/
- Markets, Utopia and the World of Things
- *Required Readings:*
- /Going to the Fair, /Selections/ /
- Marx, “Commodity Fetishism” in /Capital/
- Schivelbusch, /Railway Journey/ (finish)
- Photography and Mechanical Reproduction
- Jonathon Crary, /Techniques of the Observer/ (Selections)
- Walter Benjamin, “The Work of Art in the Age of Mechanical Reproduction”, in /Illuminations/
- Thermodynamic Worldview 2: Degeneration
- *Required Readings:*
- *William Thomson, “On the age of the sun's heat,” /MacMillan's Magazine/ 5 (1862), 288-93.
- Nordau, “Find-de-Siècle” in /Degeneration/
- Daniel Pick, /Faces of Degeneration/ (selections)
- Recommended Readings:
** 04-11
- Normalcy 1
- Statistical Persons
- Normalcy 2
- Hysteria
- Readings:
- Required:
- Francis Galton, “Probability, the Foundation of Eugenics,” The Herbert Spencer Lecture June 5, 1907 (Oxford: Clarendon Press, 1907).
- Alphonse Bertillon, “The Bertillon System,” [cite].
- Theodore M. Porter, “The Laws that Govern Chaos,” in /The Rise of Statistical Thinking, 1820-1900/ (Princeton: Princeton UP, 1986) 40-70.
- /Recommended:/
- *Deborah Coon, “Standardizing the Subject: Experimental Psychologists, Introspection, and the Quest for a Technoscientific Ideal,” /Technology and Culture /(1993), 757-783.
- Mark Seltzer, “Statistical Persons” in /Bodies and Machines/ (New York: Routledge, 1992) 93-118
** 11-11
- Imperial Science 1
- Networks and Centres of Calculation
- Imperial Science 2
- Local Knowledge Under Siege
- *Required Readings:*
- Bruno Latour, “Centres of Calculation” in /Science in Action/.
- Helen Verran, “Science as an Indigenous Knowledge System”
- collecting?
- Recommended Readings:
** 18-11
- Machine Culture 1
- Mechanization of the body
- Machine Culture 2
- Yankee engineers - electrification
- *Required Readings:*
- Marey
- 1847 group (Lenoir or Brain)
- Mark Twain, /Connecticut Yankee in King Arthur's Court/.
- Recommended Readings:
** 25-11
- Thermodynamic Worldview 2: Degeneration
- The Second Law (Entropy, Kelvin)
** 02-12
- SRailway JourneysPanoramic vision -- contraction of space and time -- machine ensemblesRequired Readings:
- *Michel Foucault, “Biopower”
- Wolfgang Schivelbusch, /The Railway Journey/, pp.1-45, 52-69
- Recommended Readings:
- Scott, /Seeing Like a State/, 11-52 (“Nature and Space”)
- Michel Foucault, /Discipline and Punish/.

* COMMENT Variables
#+begin_src emacs-lisp
(make-local-variable 'org-use-property-inheritance)
(setq org-use-property-inheritance nil)
(setq org-lms-baseurl "https://q.utoronto.ca/api/v1/")
(setq org-lms-token (password-store-get "q.utoronto.ca"))
;;(org-lms-set-keyword "ORG_LMS_COURSEID" 64706)

;; (org-lms-setup)
#+end_src

#+RESULTS:
: 11834~96SJ9HQecRwc6mUcePZGPNuwfGuqbyhRVedkAuPBxcZTew6cRkVw0gUITZPN2U7b

#+begin_src emacs-lisp
(symbol-value 'mwp-classtimes-calibrate)
#+end_src

#
# Changes not staged for commit:
#+RESULTS:
| <2019-01-03 Thu> | <2019-01-01 Tue> |

local variables need to be set at the end of the file.

** new Schedule

- degeneration
- risk societies
- subject scientific and
- Photography
- modernist math
- world war 1
- 

* COMMENT Table parsing -- doesn't belong ehre!
#+BEGIN_SRC emacs-lisp :var tbl=planstbl :results raw
(require 's)
;; (let ((headings (car tbl)))
;;   (s-join
;;    "\n"
;;    (mapcar
;;     (lambda (row)
;;       ;; (concat
;;       ;; (format "* %s\n" (car row)))
      

;;     (s-join
;;      ""
;;      (cl-map 'list 
;;              (lambda (hd x) (if (string-match "[:alpha:]" x)(concat "* "hd   "\n- " x)))
;;              headings row)))
;;     (remq 'hline (cdr tbl)))))

tbl
(mapconcat
 (lambda (row)
   (concat (if (> (length  (car row)) 0) 
               (format "* %s\n"(car row)))
           (mapconcat (lambda (s)
                        (if (> (length s) 0)
                            (format "- %s\n" s)))
                      (cdr row) ""))) tbl "")
;;tbl

#+END_SRC



# Local Variables:
# org-time-stamp-custom-formats: ("<%b. %d>" . "<%Y-%m-%d %H:%M>")
# org-mwp-classtimes-calibrate: ("<2019-09-03 Tue>" "<2019-08-29 Thu>" )
# End:

